#!/usr/bin/env python3
"""
A simple build script to ease the exclusion of selected projects from the
Maven build.
"""

import argparse
import logging
import re

from multiprocessing import cpu_count
from os import listdir
from os.path import isdir
from os.path import abspath
from subprocess import call


"""
Transformations applied to all found modules. Extend this list when needed.
Each transformation will be called with the modules name and is expected to
return a valid module name.
"""
TRANSFORMS = [
    (lambda x: x + 's' if x.endswith('test') else x),
]

"""
The elements of this list are excluded from the list of modules all together
BEFORE transformations are applied. Add modules that should never occur in any
list of modules.
"""
IGNORE = [
    'ch.hsr.ifs.cute.target',
    'ch.hsr.ifs.cute.help',
    'ch.hsr.ifs.cute.feature'
]

logging.basicConfig(format='[%(levelname)s] %(message)s', level=logging.INFO)
LOGGER = logging.getLogger("build")


def get_modules():
    """
    Retrieve the modules present in the working tree.
    """
    modules = dict()
    matcher = re.compile(r'^(?P<module>\w+.\w+\.\w+\.(\w+\.)?(?P<id>\w+).*)$')
    for entry in listdir(abspath('.')):
        if isdir(entry) and not entry.startswith('.') and entry not in IGNORE:
            match = matcher.match(entry)
            if not match:
                continue
            identifier = match.group('id')
            if identifier not in modules:
                modules[identifier] = []
            module = match.group('module')
            for transform in TRANSFORMS:
                module = transform(module)
            modules[identifier].append(module)
    return modules


def get_arguments(modules):
    """
    Retrieve the arguments passed by the user.
    """
    parser = argparse.ArgumentParser(
        prog='build',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    choices = list(modules.keys())
    choices.append('all')
    parser.add_argument(
        'modules',
        metavar='module',
        nargs='*',
        choices=choices,
        default='all',
        type=str,
        help='the module to build'
    )
    parser.add_argument(
        '-p',
        '--print-command',
        default=False,
        action='store_true',
        help='show the executed command'
    )
    parser.add_argument(
        '-s',
        '--sign-jar',
        default=False,
        action='store_true',
        help='sign the produced JARs'
    )
    parser.add_argument(
        '-j',
        '--jobs',
        metavar='N',
        default=1,
        help='how many parallel jobs to run'
    )
    parser.add_argument(
        '-f',
        '--fail-fast',
        default=False,
        action='store_true',
        help='whether or not to fail fast'
    )
    return parser.parse_args()


def handle_args(args, modules):
    """
    Handle the exclusions specified by the user.
    """
    if 'all' in args.modules:
        return {}
    excluded_modules = modules.copy()
    for key in args.modules:
        excluded_modules.pop(key)
    return excluded_modules


def get_skipstring(excluded):
    """
    Generate the Maven 'skipstring'
    """
    skips = ''
    for key, val in excluded.items():
        LOGGER.info('Skipping module \'%s\'', key.capitalize())
        for entry in val:
            skips += '!ch.hsr.ifs.cute:%s,' % entry
    return skips.strip(',')


def get_command(args, modules):
    """
    Generate the Maven command.
    """
    skips = get_skipstring(handle_args(args, modules))
    command = [
        'mvn',
        '-T%s' % args.jobs,
        '-pl \'%s\'' % skips,
        '-Djarsigner.skip=%s' % ('false' if args.sign_jar else 'true'),
        '-fae' if not args.fail_fast else '',
        'clean',
        'install',
    ]
    return command


def main():
    """
    The application
    """
    mods = get_modules()
    args = get_arguments(mods)
    comm = ' '.join(get_command(args, mods))
    if args.print_command:
        LOGGER.info('executed command: %s', comm)
    call(comm, shell=True)


if __name__ == "__main__":
    main()
