package ch.hsr.ifs.mockator.plugin;

public abstract class MockatorConstants {
  public static final String MOCKATOR_NS = "mockator";
  public static final String INIT_MOCKATOR = "INIT_MOCKATOR";
  public static final String CUTE_ASSERT_EQUAL = "ASSERT_EQUAL";
  public static final String ASSERT_ANY_ORDER = "ASSERT_ANY_ORDER";
  public static final String ASSERT_MATCHES = "ASSERT_MATCHES";
  public static final String C_ASSERT_EQUAL = "assert";
  public static final String NS_SUFFIX = "_Ns";
  public static final String CALLS = "calls";
  public static final String CALL = "call";
  public static final String MOCK_ID = "mock_id";
  public static final String PUSH_BACK = "push_back";
  public static final String SPACE = " ";
  public static final String COMMA = ",";
  public static final String CONST_KEYWORD = "const";
  public static final String STD_STRING = "std::string";
  public static final String L_PARENTHESIS = "(";
  public static final String R_PARENTHESIS = ")";
  public static final String SEMICOLON = ";";
  public static final String DOUBLE_QUOTE = "\"";
  public static final String HEADER_SUFFIX = ".h";
  public static final String SOURCE_SUFFIX = ".cpp";
  public static final String END_IF_DIRECTIVE = "#endif";
  public static final String DEFINE_DIRECTIVE = "#define";
  public static final String UNDEF_DIRECTIVE = "#undef";
  public static final String IFNDEF_DIRECTIVE = "#ifndef";
  public static final String IFDEF_DIRECTIVE = "#ifdef";
  public static final String WRAP_MACRO_PREFIX = "WRAP_";
  public static final String MOCKED_TRACE_PREFIX = "mockator_";
  public static final String TRACE_FOLDER = "trace";
  public static final String TEST_FUNCTION_PREFIX = "test";
  public static final String CUTE_NATURE = "ch.hsr.ifs.cute.ui.cutenature";
  public static final String C_ASSERT_INCLUDE = "cassert";
  public static final String SIZE_T = "size_t";
  public static final String ALL_CALLS_VECTOR_NAME = "allCalls";
  public static final String DYNAMIC_LIB_NAME = "dl";
  public static final String CUTE_SUITE = "suite";
  public static final String CUTE_NS = "cute";
}
