#!/bin/sh
# git commit hook that runs metris tests based on jdepend
# and allows a commit only if these tests have been successful
# usage: put this file with executable flag to .git/hooks

SRC_DIR=source/plugins/ch.hsr.ifs.mockator
PLUGIN_DIR=$SRC_DIR/ch.hsr.ifs.mockator.plugin
TESTS_DIR=$SRC_DIR/ch.hsr.ifs.mockator.tests
METRICS_TESTS=ch.hsr.ifs.mockator.plugin.metrics.MetricsTests
CLASS_PATH=$TESTS_DIR/lib/junit4.jar:$TESTS_DIR/lib/hamcrest-core.jar:$TESTS_DIR/bin:$TESTS_DIR/lib/jdepend-2.9.1.jar:$PLUGIN_DIR/bin

if [ -f ${TESTS_DIR}/bin/${METRICS_TESTS//.//}.class ]; then
    echo "Running metric tests..."
    java -cp $CLASS_PATH org.junit.runner.JUnitCore $METRICS_TESTS
    exit $?
fi

exit 0
